"""'Arknights'

Revision ID: 524acb118a05
Revises: 
Create Date: 2019-05-21 16:31:57.886602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '524acb118a05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('akn', 'camp',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='阵营',
               existing_nullable=True)
    op.alter_column('akn', 'characteristic',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='特性',
               existing_nullable=True)
    op.alter_column('akn', 'gender',
               existing_type=mysql.INTEGER(display_width=1),
               comment=None,
               existing_comment='性别(1为男，0为女,2为未知)',
               existing_nullable=True)
    op.alter_column('akn', 'getway',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='获取途径',
               existing_nullable=True)
    op.alter_column('akn', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='名称',
               existing_nullable=True)
    op.alter_column('akn', 'profession',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='职业',
               existing_nullable=True)
    op.alter_column('akn', 'star',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='星数',
               existing_nullable=True)
    op.alter_column('akn', 'tag',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='标签',
               existing_nullable=True)
    op.create_unique_constraint(None, 'akn', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'akn', type_='unique')
    op.alter_column('akn', 'tag',
               existing_type=mysql.VARCHAR(length=255),
               comment='标签',
               existing_nullable=True)
    op.alter_column('akn', 'star',
               existing_type=mysql.INTEGER(display_width=11),
               comment='星数',
               existing_nullable=True)
    op.alter_column('akn', 'profession',
               existing_type=mysql.VARCHAR(length=255),
               comment='职业',
               existing_nullable=True)
    op.alter_column('akn', 'name',
               existing_type=mysql.VARCHAR(length=255),
               comment='名称',
               existing_nullable=True)
    op.alter_column('akn', 'getway',
               existing_type=mysql.VARCHAR(length=255),
               comment='获取途径',
               existing_nullable=True)
    op.alter_column('akn', 'gender',
               existing_type=mysql.INTEGER(display_width=1),
               comment='性别(1为男，0为女,2为未知)',
               existing_nullable=True)
    op.alter_column('akn', 'characteristic',
               existing_type=mysql.VARCHAR(length=255),
               comment='特性',
               existing_nullable=True)
    op.alter_column('akn', 'camp',
               existing_type=mysql.VARCHAR(length=255),
               comment='阵营',
               existing_nullable=True)
    # ### end Alembic commands ###
